### PR TITLE
Close by gun generator

### PR DESCRIPTION
**Pull request by apsallid**
A new gun was recently introduced in PRs [#26065](https://github.com/cms-sw/cmssw/pull/26065) and [#26277](https://github.com/cms-sw/cmssw/pull/26277). Here we are adding this really useful tool for clustering and calibration studies to the repository. Although the instructions have been updated, this command [1] will create a photon of 60 GeV in the Scintillator part of the V10 geometry. 

[1] python SubmitHGCalPGun.py --datTier GSD --nevts 10000 --evtsperjob 50 --queue tomorrow --partID 22 --nPart 1 --thresholdMin 60 --thresholdMax 60 --etaMin 1.4 --etaMax 3.0 --zMin 429.99 --zMax 430.01 --rMin 179.99 --rMax 180.01 --pointing --gunType E --gunMode closeby --eosArea /eos/path/to/output --tag ${USER}_PDGId22_nPart1_E60_Scint_R180_Z430 [--dry-run]

@rovere @felicepantaleo @clelange

### CODE REVIEW

**Comment by clelange** [comment]
Thanks for the PR @apsallid - I propose we wait until a release has been cut that includes https://github.com/cms-sw/cmssw/pull/26065 and https://github.com/cms-sw/cmssw/pull/26277 (both are merged) until we merge this (and then update the documentation).

**Comment by clelange** [comment]
Hi @apsallid - CMSSW_10_6_0_pre4 is out, we could move ahead with this PR. Let me know if you have time to update the documentation. If not, I can take care of it next week.

**Comment by apsallid** [comment]
Hi @clelange , 

Sorry for this late reply. I think the documentation is updated now. Let me know if anything else is needed.

**Comment by clelange** [comment]
Thanks, in addition I've made a few changes in the order that things are explained.

**Pull request merged**
