### PR TITLE
Rewrite python generation

### PR DESCRIPTION
**Pull request by clelange**
The idea of having fixed python configuration that could be
customized via the usual template mechanism is too rigid and
quickly become obsolete with respect to the ongoing
development in release in terms of conditions, GT,
customizations, geometries, etc. For this reason a new
mechanisms has been introduced in order to generate and
customize the python configuration files. A shell script has
been added in order to generate python fragments using
directly cmsDriver.py commands, that should always produce
up-to-date results. The template variables have been
isolated and applied on top of those fragments. The commands
should keep on working as in the past, except that the user
now has to generate the fragments everytime.
One minor point is that the directory name must not contain
the '-' character, otherwise we are not able to import the
generated fragments.

### CODE REVIEW

**Comment by clelange** [comment]
I'll run a few tests in the next couple of days to compare it to the old scripts, but this looks very nice, and is much more flexible then the current manual procedure.

**Comment by clelange** [comment]
Hi @rovere and @cerminar - sorry about the delay. I now gave the configs a go, and in principle it's working (with some exceptions, see below), and I would like to discuss some details with you (we can also do it in the meeting):
- currently, we use a non-smeared vertex: `process.load('Configuration.StandardSequences.VtxSmearedNoSmear_cff')` vs. `process.load('IOMC.EventVertexGenerators.VtxSmearedHLLHC_cfi')` - I think for now we should just keep this vertex and have `produceSkeletons.sh` replace that line.
- the pileup mixing doesn't seem to work out of the box, it can be fixed by changing `process.load('SimGeneral.MixingModule.mixNoPU_cfi')` to `process.load('SimGeneral.MixingModule.mix_POISSON_average_cfi')` - OK?
- the geometry from the `runTheMatrix.py` command is D23 - my understanding was to stay with `Extended2023D17` and use as Era `Phase2_timing` for now. Any particular reason to use `runTheMatrix.py -w relval_upgrade -j 0 -l 22088`? I had used `runTheMatrix.py -w upgrade -j 0 -l 20234.11` recently (which gives the Era and geometry I listed, but does not solve the PU/vertex smearing).
- the repository needs to be checked out to `reco_prodtools` (mind the underscore), but that's fine, the documentation needs to be updated anyway.

Let me know what you think.

**Comment by cerminar** [comment]
Hello @clelange 

I am not sure I understand what you mean with "replace that line". What you want to obtain can just be obtained editing the cmsdriver commands in the script:

   * the non-smeared vertex can be set with: `--beamspot NoSmear`
   * the mixing can be specified for example with `--pileup 'AVE_{}_BX_25ns,{}' ".format(PU, '{"B": (-3, 3)}')`
   * the geometry option is already there, just matter of specifying the correct one

Would this satisfy your comments? Possibly we could maintain different` produceSkeletons.sh `flavors.
My 2 cents
Cheers,
G

**Comment by clelange** [comment]
Great, I didn't know that the mixing can be adjusted like that. That answers my questions. I'll just create another `produceSkeletons_D17_NoSmear_PU_Poisson.sh` or something like that to get what we've used previously, and will update the documentation. Hopefully tomorrow afternoon.

**Pull request closed without merging**
