### PR TITLE
bash version of zshell script

### PR DESCRIPTION
**Pull request by b-fontana**
I wrote a bash version of the zshell script currently being used, because I am more familiar with bash. There is small added functionality: the user has to specify which folders he/she wants to process, using the MYDIRS variable. The zshell version currently runs on all the folders, which I believe is not the intended behaviour.

### CODE REVIEW

**Comment by clelange** [comment]
Hi @b-fontana - thanks for your contribution!

In principle, your bash script could just replace the script that I wrote some time ago, I just added it because I thought it was useful for others as well. Regarding the `MYDIRS` variable, it basically does the same thing as adding a `grep` command at https://github.com/CMS-HGCAL/reco-prodtools/blob/master/submitNextStep.sh#L13 and therefore also requires editing the file by hand.
What about making the script a bit more flexible by adding a parameter that can be passed to it on the command line instead?

**Comment by b-fontana** [comment]
Hello @clelange: I implemented and tested the change you suggested. The script has to be run as follows:

`bash submitNextStep data_folder_1 data_folder_2 ...`

I hope this is what you intended. Cheers!

**Comment by b-fontana** [comment]
By the way, although this is unrelated to the current pull request, could you perhaps change the name of the repository to 'reco_prodtools' (note the underscore)? I got stuck for a while because I forgot to rename my local folder.

**Comment by clelange** [comment]
@b-fontana Just to let you know why I haven't merged this: I'm currently debugging some issues in the scripts and the ntupliser, and I just didn't have the time to test your script. I think I should manage next week.

Regarding the renaming of the repository: since there exist quite a few forks and links from twikis to it, we'd have to make that a more concerted effort. While the use of the underscore is clearly pointed out in the README, it seems not everyone is reading it (...), so it would make things easier.

**Pull request merged**
